server:
  port: 8899
  
spring: 
  application:
    name: Front-Viewer-Service
  data:
    mongodb:
      host:  127.0.0.1
      database: schoolData
      port: 27017
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:mem:msdb
    username: root
    password: root
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2

pivotal:
  validate-service:
    login-validate: Validate-School-Data/adminValidate/login
