server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
      - id: School-Data-Read-Service
        uri: http://localhost:8010/
        predicates:
        - Path=/**
      - id: consumerModule
        uri: http://localhost:8020/
        predicates:
        - Path=/**